version: '3'

services:
  cool_app:
    build: ./cool_app
    ports:
      - "127.0.0.1:8001:8001"
    links:
      - postgres:postgres
    volumes:
      - ./cool_app:/code
    env_file: .env
    command: ./run_app.sh

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file: .env
    restart: always
  
volumes:
  postgres:
